const raceDay = require("./raceDay.js");

test("a random number should be generated by raceDay.js", () => {
  const raceNumber = raceDay.generateRaceNumber();
  expect(raceNumber).toBeDefined();
  expect(typeof raceNumber).toBe("number");
});
